# Generated by Django 3.0.3 on 2020-02-28 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('brewery_id', models.IntegerField(default=-1)),
                ('name', models.CharField(default='Unknown beer', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown brewery', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown Category', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Geocode',
            fields=[
                ('id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(default=-1)),
                ('longitude', models.FloatField(default=-1)),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_data.Brewery')),
            ],
        ),
    ]
