# Generated by Django 3.0.3 on 2020-02-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer_data', '0003_auto_20200228_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='beer_data.Category'),
            preserve_default=False,
        ),
    ]
