# Generated by Django 3.0.3 on 2020-02-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_data', '0004_beer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='beer_count',
            field=models.IntegerField(default=0),
        ),
    ]
