# Generated by Django 3.0.3 on 2020-02-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_data', '0005_brewery_beer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='latitude',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='brewery',
            name='longitude',
            field=models.FloatField(default=-1),
        ),
        migrations.DeleteModel(
            name='Geocode',
        ),
    ]
